In [32]:
import pandas as pd
data = pd.read_csv('/home/leandro/Downloads/caracteristicas-com-af_new.csv',sep=';',decimal=',')

ParserError: Error tokenizing data. C error: Expected 605 fields in line 4, saw 610

In [30]:
data.head()

,@@class@@,Festrutural,quantidadeNAD,quantidadeMagnesio,quantidadeLigacoesDissulfeto,quantidadeFAD,quantidadeFerro,quantidadeATP,quantidadeCalcio,quantidadeCobre,...,Ftrincas_134,Ftrincas_135,Ftrincas_136,Ftrincas_137,Ftrincas_138,Ftrincas_139,Ftrincas_140,Ftrincas_141,Ftrincas_142,Ftrincas_143
0,Hidrolases,-1.384,"0,0,0,0,0,0,0,0","0,1265060241","0,0120481928","0,078313253",0.084337,"0,0240963855",0.048193,"0,0120481928",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Hidrolases,0.495,"0,0,0,0,0,0,0,0","0,1146131805","0,005730659","0,0458452722",0.054441,"0,0200573066",0.077364,"0,0286532951",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Hidrolases,-2.330,"0,0,0,0,0,0","0,0060240964",0,"0,0939597315",0.006711,"0,0536912752",0.080537,"0,0201342282",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Isomerases,-0.626,"0,0,0,0,0,0,0,0","0,0256410256","0,0085470085","0,0512820513",0.055556,"0,0683760684",0.029915,"0,0213675214",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Liases,-0.817,"0,0,0,0,0,0,0,0","0,0501930502","0,0038610039","0,0733590734",0.050193,"0,0463320463",0.084942,"0,0463320463",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN